# Generated by Django 4.1.7 on 2023-02-17 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_proiect_final', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Proiect Final MyBlog', max_length=255),
        ),
    ]
